ADDED_TO_FAV = "BOISSON AJOUTÉE AUX FAVORIS"
ADDED_TO_FAV_FOOD = "ALIMENT AJOUTÉ AUX FAVORIS"
ADDED_TO_FAV_PAGE = 205
ADDED_TO_FAV_FOOD_PAGE = 105
BETTER_BEVERAGES = "CHOISISSEZ UNE MEILLEURE BOISSON"
BETTER_FOOD = "CHOISISSEZ UN MEILLEUR ALIMENT"
BEVERAGES = "Boissons"
BRANDS = "brands"
BRAND_NAME_MAX_LENGTH = 25
CATEGORIES = "categories"
CATEGORIES_TO_BE_DELETED = []

CATEGORY_NAME_MAX_LENGTH = 45
CHOOSE_A_CATEGORY = "CHOISISSEZ UNE CATÉGORIE"
CHOOSE_A_PRODUCT = "CHOISISSEZ UN PRODUIT"
CREATE_DB = "CRÉER LA BASE DE DONNÉES"
CREATE_DB_PAGE = -100
DATABASE_CREATED = "DATABASE HAS BEEN CREATED"
DB_HAS_BEEN_CREATED = -3
DELETED_FROM_FAV = "PRODUIT SUPPRIMÉ DES FAVORIS"
FAVORITE_SUBSTITUTE_DELETED = 303
DETAILS_OF_A_BEVERAGE_PROD_PAGE = 203
DETAILS_OF_A_FOOD_PROD_PAGE = 103
ERROR_COLOR = "\033[0;31;1m"
FAVORITES = "MES FAVORIS"
FAVORITES_PAGE = 301
FAVS_FOR_A_PRODUCT = "LES SUBSTITUTS FAVORIS POUR UN PRODUIT"
FOOD = "Aliments"
GET_A_BETTER_BEVERAGE_PAGE = 204
GET_A_BETTER_FOOD_PAGE = 104
GET_PROD_FROM_A_BEVERAGE_PAGE = 202
GET_PROD_FROM_A_FOOD_PAGE = 102
HOME = "ACCUEIL"
HOME_PAGE = 0
INDEX_OF_FIRST_CAT = 10
INDEX_OF_FIRST_PROD = 10
INGREDIENTS_MAX_LENGTH = 300
INITIAL = "PAGE INITIALE"
INITIAL_PAGE = -2
LIST_OF_SUBSTITUTES_FOR_1_PRODUCT = 302
LOOK_FOR_A_BETTER_PRODUCT = 4
MAX_PRODS_DISPLAYED = 7
MINIMAL_CATEGORY_LENGTH = 3
NBR_OF_CATEGORIES = 30
NBR_OF_PRODUCTS = 30
NBR_OF_FIELDS_BY_PRODUCT = 6
NEXT_CATEGORIES = 9
NEXT_PRODUCTS = 9
NORMAL_COLOR = "\033[0;0;0m"
NUTRISCORE_MAX_LENGTH = 2
OK = 1
PREVIOUS_CATEGORIES = 7
PREVIOUS_PRODUCTS = 7
PRIMARY_MENU = """
Que souhaitez-vous faire ?
[1] Substituer une boisson
[2] Substituer un aliment
[3] Voir mes aliments de substitution"""
PRODUCT = "product"
PRODUCT_NAME_MAX_LENGTH = 55
PRODUCT_DETAILS = "DÉTAILS DU PRODUIT"
PRODUCTS_PER_PAGE = 20  # Il faudra le régler à 2000 ===============
PROGRAM_QUIT_BY_USER = "Program quit by user"
ROOT_BRANCH = -1
LIST_OF_BEVERAGES_THAT_ARE_FOOD_TOO = [
    "Aliments",
    "Aliments D'Origine Vegetale",
    "Aliments Et Boissons A Base De Vegetaux",
    "Cereales",
    "Gaspacho",
    "Gazpacho",
    "Legumes",
    "Legumineuses",
    "Petit-Dejeuners",
    "Plats",
    "Refrigeres",
    "Soupes"]
STORE_NAME_MAX_LENGTH = 35
STARTER = "STARTER"
STORES = "stores"
SUBSTITUTE_A_FOOD_PAGE = 101
SUBSTITUTE = "SUBSTITUER UN PRODUIT"
SUBSTITUTE_A_BEVERAGE_PAGE = 201
TRUNK_BRANCH = 0
URL_MAX_LENGTH = 200
