ADD_TO_FAV_PAGE = 205
BETTER_BEVERAGES = "CHOISISSEZ UNE MEILLEURE BOISSON"
BEVERAGES = "Boissons"
BRANDS = "brands"
BRAND_NAME_MAX_LENGTH = 25
CATEGORIES = "categories"
CATEGORIES_TO_BE_DELETED = []

CATEGORY_NAME_MAX_LENGTH = 45
CHOOSE_A_CATEGORY = "CHOISISSEZ UNE CATÉGORIE"
CHOOSE_A_PRODUCT = "CHOISISSEZ UN PRODUIT"
DETAILS_OF_A_BEVERAGE_PROD_PAGE = 203
GET_PROD_FROM_A_SUBCAT_PAGE = 202
INDEX_OF_FIRST_CAT = 10
INDEX_OF_FIRST_PROD = 10
INGREDIENTS_MAX_LENGTH = 300
CREATE_DB = "CRÉER LA BASE DE DONNÉES"
CREATE_DB_PAGE = -100
DATABASE_CREATED = "DATABASE HAS BEEN CREATED"
DB_HAS_BEEN_CREATED = -3
ERROR_COLOR = "\033[0;31;1m"
FAVORITES = "MES FAVORIS"
FAVORITES_PAGE = 301
FOOD = "Aliments"
GET_A_BETTER_BEVERAGE_PAGE = 204
HOME = "ACCUEIL"
HOME_PAGE = 0
INITIAL = "PAGE INITIALE"
INITIAL_PAGE = -2
LOOK_FOR_A_BETTER_PRODUCT = 4
MAX_PRODS_DISPLAYED = 10
MINIMAL_CATEGORY_LENGTH = 3
NBR_OF_CATEGORIES = 30
NBR_OF_PRODUCTS = 30
NBR_OF_FIELDS_BY_PRODUCT = 6
NEXT_CATEGORIES = 9
NEXT_PRODUCTS = 9
NORMAL_COLOR = "\033[0;0;0m"
NUTRISCORE_MAX_LENGTH = 2
PREVIOUS_CATEGORIES = 7
PREVIOUS_PRODUCTS = 7
PRIMARY_MENU = """
Que souhaitez-vous faire ?
[1] Substituer une boisson
[2] Substituer un aliment
[3] Voir mes aliments de substitution"""
PRODUCT = "product"
PRODUCT_NAME_MAX_LENGTH = 55
PRODUCT_DETAILS = "DÉTAILS DU PRODUIT"
PRODUCTS_PER_PAGE = 20  # Il faudra le régler à 2000
PROGRAM_QUIT_BY_USER = "Program quit by user"
ROOT_BRANCH = -1
LIST_OF_BEVERAGES_THAT_ARE_FOOD_TOO = [
    "Cereales",
    "Gaspacho",
    "Gazpacho",
    "Legumes",
    "Legumineuses",
    "Plats",
    "Refrigeres",
    "Soupes"]
STORE_NAME_MAX_LENGTH = 35
STARTER = "STARTER"
STORES = "stores"
SUBSTITUTE_A_FOOD = 101
SUBSTITUTE = "SUBSTITUER UN PRODUIT"
SUBSTITUTE_A_BEVERAGE_PAGE = 201
TRUNK_BRANCH = 0
